# Generated by Django 4.1.4 on 2022-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(null=True, to='product_module.producttags', verbose_name='برچسب های محصول'),
        ),
    ]
