# Generated by Django 4.1.4 on 2022-12-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_remove_producttags_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='product_module.producttags', verbose_name='برچسب های محصول'),
        ),
    ]
