# Generated by Django 4.1.4 on 2022-12-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_slug_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
