# Generated by Django 4.1.4 on 2022-12-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_product_created_product_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Updated',
            new_name='updated',
        ),
    ]
