# Generated by Django 4.1.4 on 2023-01-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='قیمت نهایی تکی محصول'),
        ),
    ]
