# Generated by Django 4.1.4 on 2023-01-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlinkbox',
            options={'verbose_name': 'دسته بندی لینک های فوتر', 'verbose_name_plural': 'دسته بندی لینک های فوتر'},
        ),
        migrations.AddField(
            model_name='footerlinkbox',
            name='is_active',
            field=models.BooleanField(null=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
