# Generated by Django 4.1.4 on 2023-01-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_footerlinkbox_options_footerlinkbox_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinkbox',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
