# Generated by Django 4.1.4 on 2023-01-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='send_email',
            field=models.BooleanField(default=False, editable=False, verbose_name='ایمیل پاسخ ارسال شده'),
        ),
    ]
