# Generated by Django 4.1.4 on 2023-01-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_articlecategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, verbose_name='عنوان در لینک'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='عنوان مقاله'),
        ),
    ]
