# Generated by Django 4.1.4 on 2023-01-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
