# Generated by Django 4.1.4 on 2023-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_user_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/user_profile/', verbose_name='تصویر پروفایل'),
        ),
    ]
